apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: client
  - protocol: TCP
    port: 16379
    targetPort: 16379
    name: gossip
